"""init6

Revision ID: 8696476fa0aa
Revises: 0fe33c3fdb3e
Create Date: 2023-12-05 22:02:52.521486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8696476fa0aa'
down_revision: Union[str, None] = '0fe33c3fdb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'career')
    op.drop_column('doctor', 'education')
    op.add_column('patient', sa.Column('birth_date', sa.Date(), nullable=True))
    op.drop_column('patient', 'attribs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('attribs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('patient', 'birth_date')
    op.add_column('doctor', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('doctor', sa.Column('career', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
