"""init5

Revision ID: 0fe33c3fdb3e
Revises: 5738c06358a8
Create Date: 2023-12-04 03:59:06.069940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe33c3fdb3e'
down_revision: Union[str, None] = '5738c06358a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'sender_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
