"""init

Revision ID: fb07a5f46f2b
Revises: 8696476fa0aa
Create Date: 2023-12-07 03:14:28.879478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb07a5f46f2b'
down_revision: Union[str, None] = '8696476fa0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=False)
    op.add_column('chat', sa.Column('doctor_user_id', sa.Integer(), nullable=True))
    op.add_column('chat', sa.Column('patient_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('chat_patient_id_fkey', 'chat', type_='foreignkey')
    op.drop_constraint('chat_doctor_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'patient', ['patient_user_id'], ['user_id'])
    op.create_foreign_key(None, 'chat', 'doctor', ['doctor_user_id'], ['user_id'])
    op.drop_column('chat', 'patient_id')
    op.drop_column('chat', 'doctor_id')
    op.drop_index('ix_message_id', table_name='message')
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.create_index('ix_message_id', 'message', ['id'], unique=False)
    op.add_column('chat', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_doctor_id_fkey', 'chat', 'doctor', ['doctor_id'], ['user_id'])
    op.create_foreign_key('chat_patient_id_fkey', 'chat', 'patient', ['patient_id'], ['user_id'])
    op.drop_column('chat', 'patient_user_id')
    op.drop_column('chat', 'doctor_user_id')
    op.drop_index(op.f('ix_attachment_id'), table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
