"""init3

Revision ID: 0d7a9cd84dc4
Revises: 0f1c33e67a6c
Create Date: 2023-12-07 16:19:03.929829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7a9cd84dc4'
down_revision: Union[str, None] = '0f1c33e67a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accesstoken_id', table_name='accesstoken')
    op.drop_column('accesstoken', 'id')
    op.drop_index('ix_attachment_id', table_name='attachment')
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=True)
    op.drop_index('ix_message_id', table_name='message')
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.create_index('ix_message_id', 'message', ['id'], unique=False)
    op.drop_index(op.f('ix_attachment_id'), table_name='attachment')
    op.create_index('ix_attachment_id', 'attachment', ['id'], unique=False)
    op.add_column('accesstoken', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_accesstoken_id', 'accesstoken', ['id'], unique=False)
    # ### end Alembic commands ###
