"""init3

Revision ID: ecd28781f8e7
Revises: e2519cb0ecbd
Create Date: 2023-12-07 16:08:07.871990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecd28781f8e7'
down_revision: Union[str, None] = 'e2519cb0ecbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accesstoken_created_at', table_name='accesstoken')
    op.drop_index('ix_accesstoken_id', table_name='accesstoken')
    op.drop_table('accesstoken')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesstoken',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=43), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='accesstoken_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', 'id', name='accesstoken_pkey')
    )
    op.create_index('ix_accesstoken_id', 'accesstoken', ['id'], unique=False)
    op.create_index('ix_accesstoken_created_at', 'accesstoken', ['created_at'], unique=False)
    # ### end Alembic commands ###
